export let country_list = {
    "AE": ["AED", "Arab Emirates dirham"],
    "AF": ["AFN", "Afghan afghani"],
    "AG": ["XCD", "East Caribbean dollar"],
    "AL": ["ALL", "Albanian lek"],
    "AM": ["AMD", "Armenian dram"],
    "AN": ["ANG", "Netherlands Antillean guilder"],
    "AO": ["AOA", "Angolan kwanza"],
    "AQ": ["AQD", "Antarctic dollar"],
    "AR": ["ARS", "Argentine peso"],
    "AU": ["AUD", "Australian dollar"],
    "AZ": ["AZN", "Azerbaijani manat"],
    "BA": ["BAM", "Bosnia convertible mark"],
    "BB": ["BBD", "Barbadian dollar"],
    "BD": ["BDT", "Bangladeshi taka"],
    "BE": ["XOF", "West African CFA franc"],
    "BG": ["BGN", "Bulgarian lev"],
    "BH": ["BHD", "Bahraini dinar"],
    "BI": ["BIF", "Burundian franc"],
    "BM": ["BMD", "Bermudian dollar"],
    "BN": ["BND", "Brunei dollar"],
    "BO": ["BOB", "Bolivian boliviano"],
    "BR": ["BRL", "Brazilian real"],
    "BS": ["BSD", "Bahamian dollar"],
    "BV": ["NOK", "Norwegian krone"],
    "BW": ["BWP", "Botswanan pula"],
    "BY": ["BYR", "Belarusian ruble"],
    "BZ": ["BZD", "Belize dollar"],
    "CA": ["CAD", "Canadian dollar"],
    "CD": ["CDF", "Congolese franc"],
    "CF": ["XAF", "Central African CFA franc"],
    "CH": ["CHF", "Swiss franc"],
    "CL": ["CLP", "Chilean peso"],
    "CN": ["CNY", "Chinese yuan"],
    "CO": ["COP", "Colombian peso"],
    "CR": ["CRC", "Costa Rican colón"],
    "CU": ["CUP", "Cuban peso"],
    "CV": ["CVE", "Cape Verdean escudo"],
    "CY": ["CYP", "Cypriot pound"],
    "CZ": ["CZK", "Czech koruna"],
    "DJ": ["DJF", "Djiboutian franc"],
    "DK": ["DKK", "Danish krone"],
    "DO": ["DOP", "Dominican peso"],
    "DZ": ["DZD", "Algerian dinar"],
    "EC": ["ECS", "Ecuadorian sucre"],
    "EE": ["EEK", "Estonian kroon"],
    "EG": ["EGP", "Egyptian pound"],
    "ET": ["ETB", "Ethiopian birr"],
    "EU": ["EUR", "Euro"],
    "FJ": ["FJD", "Fijian dollar"],
    "FK": ["FKP", "Falkland Islands pound"],
    "GB": ["GBP", "British pound"],
    "GE": ["GEL", "Georgian lari"],
    "GG": ["GGP", "Guernsey pound"],
    "GH": ["GHS", "Ghanaian cedi"],
    "GI": ["GIP", "Gibraltar pound"],
    "GM": ["GMD", "Gambian dalasi"],
    "GN": ["GNF", "Guinean franc"],
    "GT": ["GTQ", "Guatemalan quetzal"],
    "GY": ["GYD", "Guyanese dollar"],
    "HK": ["HKD", "Hong Kong dollar"],
    "HN": ["HNL", "Honduran lempira"],
    "HR": ["HRK", "Croatian kuna"],
    "HT": ["HTG", "Haitian gourde"],
    "HU": ["HUF", "Hungarian forint"],
    "ID": ["IDR", "Indonesian rupiah"],
    "IL": ["ILS", "Israeli new shekel"],
    "IN": ["INR", "Indian rupee"],
    "IQ": ["IQD", "Iraqi dinar"],
    "IR": ["IRR", "Iranian rial"],
    "IS": ["ISK", "Icelandic króna"],
    "JM": ["JMD", "Jamaican dollar"],
    "JO": ["JOD", "Jordanian dinar"],
    "JP": ["JPY", "Japanese yen"],
    "KE": ["KES", "Kenyan shilling"],
    "KG": ["KGS", "Kyrgyzstani som"],
    "KH": ["KHR", "Cambodian riel"],
    "KM": ["KMF", "Comorian franc"],
    "KP": ["KPW", "North Korean won"],
    "KR": ["KRW", "South Korean won"],
    "KW": ["KWD", "Kuwaiti dinar"],
    "KY": ["KYD", "Cayman Islands dollar"],
    "KZ": ["KZT", "Kazakhstani tenge"],
    "LA": ["LAK", "Lao kip"],
    "LB": ["LBP", "Lebanese pound"],
    "LK": ["LKR", "Sri Lankan rupee"],
    "LR": ["LRD", "Liberian dollar"],
    "LS": ["LSL", "Lesotho loti"],
    "LT": ["LTL", "Lithuanian litas"],
    "LV": ["LVL", "Latvian lats"],
    "LY": ["LYD", "Libyan dinar"],
    "MA": ["MAD", "Moroccan dirham"],
    "MD": ["MDL", "Moldovan leu"],
    "MG": ["MGA", "Malagasy ariary"],
    "MK": ["MKD", "Macedonian denar"],
    "MM": ["MMK", "Burmese kyat"],
    "MN": ["MNT", "Mongolian tögrög"],
    "MO": ["MOP", "Macanese pataca"],
    "MR": ["MRO", "Mauritanian ouguiya"],
    "MT": ["MTL", "Maltese lira"],
    "MU": ["MUR", "Mauritian rupee"],
    "MV": ["MVR", "Maldivian rufiyaa"],
    "MW": ["MWK", "Malawian kwacha"],
    "MX": ["MXN", "Mexican peso"],
    "MY": ["MYR", "Malaysian ringgit"],
    "MZ": ["MZN", "Mozambican metical"],
    "NA": ["NAD", "Namibian dollar"],
    "NC": ["XPF", "CFP franc"],
    "NG": ["NGN", "Nigerian naira"],
    "NI": ["NIO", "Nicaraguan córdoba"],
    "NP": ["NPR", "Nepalese rupee"],
    "NZ": ["NZD", "New Zealand dollar"],
    "OM": ["OMR", "Omani rial"],
    "PA": ["PAB", "Panamanian balboa"],
    "PE": ["PEN", "Peruvian sol"],
    "PG": ["PGK", "Papua New Guinean kina"],
    "PH": ["PHP", "Philippine peso"],
    "PK": ["PKR", "Pakistani rupee"],
    "PL": ["PLN", "Polish złoty"],
    "PY": ["PYG", "Paraguayan guaraní"],
    "QA": ["QAR", "Qatari riyal"],
    "RO": ["RON", "Romanian leu"],
    "RS": ["RSD", "Serbian dinar"],
    "RU": ["RUB", "Russian ruble"],
    "RW": ["RWF", "Rwandan franc"],
    "SA": ["SAR", "Saudi riyal"],
    "SB": ["SBD", "Solomon Islands dollar"],
    "SC": ["SCR", "Seychellois rupee"],
    "SD": ["SDG", "Sudanese pound"],
    "SE": ["SEK", "Swedish krona"],
    "SG": ["SGD", "Singapore dollar"],
    "SK": ["SKK", "Slovak koruna"],
    "SL": ["SLL", "Sierra Leonean leone"],
    "SO": ["SOS", "Somali shilling"],
    "SR": ["SRD", "Surinamese dollar"],
    "ST": ["STD", "São Tomé & Príncipe dobra"],
    "SV": ["SVC", "Salvadoran colón"],
    "SY": ["SYP", "Syrian pound"],
    "SZ": ["SZL", "Swazi lilangeni"],
    "TH": ["THB", "Thai baht"],
    "TJ": ["TJS", "Tajikistani somoni"],
    "TM": ["TMT", "Turkmenistani manat"],
    "TN": ["TND", "Tunisian dinar"],
    "TO": ["TOP", "Tongan paʻanga"],
    "TR": ["TRY", "Turkish lira"],
    "TT": ["TTD", "Trinidad and Tobago dollar"],
    "TW": ["TWD", "New Taiwan dollar"],
    "TZ": ["TZS", "Tanzanian shilling"],
    "UA": ["UAH", "Ukrainian hryvnia"],
    "UG": ["UGX", "Ugandan shilling"],
    "US": ["USD", "United States dollar"],
    "UY": ["UYU", "Uruguayan peso"],
    "UZ": ["UZS", "Uzbekistani soʻm"],
    "VE": ["VEF", "Venezuelan bolívar"],
    "VN": ["VND", "Vietnamese đồng"],
    "VU": ["VUV", "Vanuatu vatu"],
    "YE": ["YER", "Yemeni rial"],
    "ZA": ["ZAR", "South African rand"],
    "ZM": ["ZMK", "Zambian kwacha"],
    "ZW": ["ZWD", "Zimbabwean dollar"]
};